### ISSUE TITLE
Treat Core installer

### ISSUE THREAD

**Issue by peddinti** [louismullie/treat#107]
Hi,

Treat is included in one of my rails web apps and i added Treat::Core::Installer.install 'english' as part of the <environment>.rb so it means this command gets run after every deployement. 

However it appears that it is installing and taking a long time everytime i run this command .. i was under the impression this is a one of installation thing. is that not the case?

Thanks
VMK

**Comment by louismullie** [comment]
Yes, this is a one-time thing. The install command will download large model files that are required for different libraries to work. As long as you have persistence in your deployment environment, you only need to do this on the first deploy. 

I will close this for now, let me know if you have any further questions.

**Comment by peddinti** [comment]
What location does this model files are downloaded to? because with every deployment the application directory is different. if it is downloading relative to the application directory then it is a problem.

can i configure that path?

**Comment by louismullie** [comment]
Yep, you can configure the path here: https://github.com/louismullie/treat/wiki/Manual#paths
