### ISSUE TITLE
Server www.louismullie.com down ? :-(

### ISSUE THREAD

**Issue by GaetanJUVIN** [louismullie/treat#113]
I'm running Treat.install with default optiions (1)
And got next:

Treat::Exception: Couldn't download www.louismullie.com/treat/punkt/english.yaml. (response code was not 200 OK, but was 404. )

Actually i have found english.yaml on google.. i have modify my /etc/hosts in order to lie to my computer and pass this step. But the next one is: stanford-core-nlp-full.zip
And this one I did not find it :-(

Can you reup you server or push all required file somewhere we can download it ? :p 
In advance thanks! 

Gaëtan

**Comment by javierarce** [comment]
Yep, the server seems to be down :( 

I've just sent a message to Louis on Twitter.

**Comment by garside** [comment]
Still down. Much sads. Ow. :dog:

**Comment by garside** [comment]
`http://webcache.googleusercontent.com/search?q=cache:babXiEf_DaAJ:louismullie.com/treat/punkt/english.yaml+&cd=1&hl=en&ct=clnk&gl=us`

Is the google cache of the file.

wget/copy-paste this file onto your local machine, then open an irb and type

```ruby
require 'treat'
Treat.paths.models
```

Put this file in the directory that `Treat.paths.models` returns as `punkt/english.yaml` and then you should be able to continue with the install step.

Might need to `mkdir punkt` in that directory first.

**Comment by GaetanJUVIN** [comment]
Yes... and the next step will be stanford-core-nlp-full.zip, have you found it ? :p 

Gaëtan

**Comment by garside** [comment]
Nope! Still struggling through this one. First time installs. :(

**Comment by garside** [comment]
Yea I doubt a cache of the zip is accessible. Aw well. :(

**Comment by DavidBates** [comment]
If you have it installed somewhere you can get the files from the tmp directory and put them in place.

**Comment by GaetanJUVIN** [comment]
@DavidBates can you upload theses files somewhere in order for us to succeed our first time install ? :)

**Comment by whistlerbrk** [comment]
How about we set up mirrors

**Comment by garside** [comment]
Yea i've got a bunch of s3 space I don't mind using. If someone can put the files up publicly somewhere, I don't mind throwing them up in the bucket. Would you be able to make the files internet accessible somehow @DavidBates ?

**Comment by DavidBates** [comment]
https://www.dropbox.com/s/h4ngtszvcw4ob9r/stanford-core-nlp-all.zip?dl=0 
https://www.dropbox.com/s/ykk58j91ujoqq4q/english.yaml?dl=0

**Comment by DavidBates** [comment]
I'll leave those up through the night for someone to replicate

**Comment by GaetanJUVIN** [comment]
@DavidBates thanks man ! :)

**Comment by garside** [comment]
Thanks much!

These files should now be available on `https://s3.amazonaws.com/static-public-assets/treat/`

All you should need to do is edit your gem (root locations may vary)

`~/.rvm/gems/ruby-X.Y.Z/gems/treat-A.B.C/lib/treat/core/installer.rb`

And change `line 8` from

`Server = 'www.louismullie.com'`

to

`Server = 's3.amazonaws.com/static-public-assets'`

**Comment by louismullie** [comment]
Sorry about that peeps, now fixed.

**Comment by kunya2415** [comment]
**Problem is open again**. server returns **502** response code

**Comment by an-nasir** [comment]
@garside the s3 says 
The specified bucket does not exist.
Is there any fix yet? I am on ruby 2.5.0, rails 5.1.4
