### ISSUE TITLE
Please add a note to the README that this repo is unmaintained

### ISSUE THREAD

**Issue by twelvelabs** [louismullie/treat#121]
- The `birch` dependency does not build on ruby >= 2.2: https://github.com/louismullie/birch/issues/11 ...  I worked around this referencing this fork in my Gemfile: https://github.com/louismullie/birch/pull/12
- Installing treat via Bundler and attempting to run `Treat::Core::Installer.install` will nuke existing installs of `nokogiri` before attempting to install it. Treat's install attempt will fail and many of the other dependencies will fail. The gem does not seem to play well with existing apps (in this case Rails) that use bundler for managing gems.
- Even if I had been able to successfully install the gems above, the installer later attempts to pull down assets from an inaccessible server: https://github.com/louismullie/treat/issues/117 and https://github.com/louismullie/treat/issues/119

I respect the effort the maintainers have put into this project, but my searches suggested this was the leading NLP gem for Ruby and I just spent a considerable time just trying to get it installed without much success. Putting this here as a warning to others.

**Comment by preston** [comment]
+1!

**Comment by j-mcnally** [comment]
almost all the deps have been forked and updated.

```
gem 'birch', github: "billthompson/birch", branch: "birch-ruby22"
gem "treat", github: 'xiao0720/treat'
gem 'stanford-core-nlp', github: 'frankel/stanford-core-nlp'
gem "bind-it", github: "j-mcnally/bind-it"
```

Is what i've ended with so far, still having a few issues here and there. will keep yall posted.

**Comment by j-mcnally** [comment]
instead of doing the install via the cmd line, i opt'ed to put together my own jars and have been working through deps. then i just added

```
# Treat Deps
gem 'linguistics'
gem 'engtagger'
gem 'open-nlp'
gem 'stanford-core-nlp', github: 'frankel/stanford-core-nlp'
gem 'rwordnet'
gem 'scalpel'
gem 'fastimage'
gem 'decisiontree'
gem 'whatlanguage'

gem 'nickel'
gem 'tactful_tokenizer'
gem 'srx-english'
gem 'punkt-segmenter'
gem 'chronic'
gem 'uea-stemmer'
gem 'rbtagger'
gem 'ruby-stemmer'
gem 'rb-libsvm'
gem 'tomz-liblinear-ruby-swig'
gem 'ruby-fann'
gem 'fuzzy-string-match'
gem 'levenshtein-ffi'
gem 'tf-idf-similarity'
gem 'kronic'
```

in my gem file, and its working for the most part.

**Comment by MindRave** [comment]
@twelvelabs Just out of curiosity, which gem did you end up going with after all (and if...)?

**Comment by louismullie** [comment]
https://github.com/louismullie/birch/commit/27f81e35005a42d6d30e102cc59222c20399d987 fixes issue with Birch
