### ISSUE TITLE
Missed file during installation

### ISSUE THREAD

**Issue by amishyn** [louismullie/treat#3]
I'm runnint Treat.install and select default optiions (1)
And got next:

Treat::Exception: Couldn't download www.louismullie.com/treat/punkt/english.yaml. (response code was not 200 OK, but was 404. )

**Comment by GaetanJUVIN** [comment]
Hey Louis,

your server seems to be down ? :-(

Gaëtan

**Comment by fhinson** [comment]
+1, your server appears to be down

**Comment by javierarce** [comment]
@fhinson: There's an open ticket regarding this issue here https://github.com/louismullie/treat/issues/113
