### ISSUE TITLE
Error when calling apply(:topics)

### ISSUE THREAD

**Issue by felipeclopes** [louismullie/treat#86]
I added the Treat gem into a Rails 4 application and when I try to extract entities from a text I get the following exception:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /user/.rvm/gems/ruby-2.1.2@project/gems/treat-2.1.0/models/reuters/industry.xml
from /user/.rvm/gems/ruby-2.1.2@project/gems/treat-2.1.0/lib/treat/workers/extractors/topics/reuters.rb:57:in `read'
```

So I know I can download these files from http://louismullie.com/treat/reuters/, is there any way that his could be done in the installation of the gem?

**Comment by krishaish** [comment]
I treat this step. but still this doesn't resolved my problem. 
No such file or directory @ rb_sysopen - /home/hari/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/treat-2.1.0/models/reuters/industry.xml
