### ISSUE TITLE
When bundling treat in a rails app, no rake tasks for installing language packs appear.

### ISSUE THREAD

**Issue by KurtRMueller** [louismullie/treat#88]
According to this link, https://github.com/louismullie/treat/wiki/Manual#getting-language-packages, there should be this rake task: `rake treat:install[english]`.

Unfortunately, running `rake -T` shows that there are no `Treat` rake tasks present.

Can anybody help out? Thanks!

**Comment by louismullie** [comment]
The rake task provided is for development purposes only. 

However, it should be extremely easy to create your own rake task:

```ruby
  # Installs a language pack (default to english).
  # A language pack is a set of gems, binaries and
  # model files that support the various workers 
  # that are available for that particular language.
  # Syntax: rake treat:install (installs english)
  # - OR -  rake treast:install[some_language]
  task :install, [:language] do |t, args|
    language = args.language || 'english'
    Treat::Core::Installer.install(language)
  end
```
